### ISSUE TITLE
main.cpp Line 280 Error

### ISSUE THREAD

**Issue by yuen33** [junyanz/FaceDemo#1]
invalid null pointer as following:
![error](https://cloud.githubusercontent.com/assets/2410684/20095135/37dea1b2-a5df-11e6-9376-9fb8f0080827.PNG)

**Comment by junyanz** [comment]
It seems that you have some problems with argument parser. Could you provide more details? (For example, how did you call the function?)
An example for command line interface:
./FaceDemo image ./data/bush.jpg
