### ISSUE TITLE
Error facedetect !!!! only eye and nose

### ISSUE THREAD

**Issue by anthonyyuan** [junyanz/FaceDemo#3]
[](url)

**Comment by junyanz** [comment]
The face detection/alignment module failed in your test photo. I use the opencv face detector, and CLM tracker to detect the points of eyes, mouth, and nose. You can replace the detector/alignment module with the latest and more accurate stuff.

**Comment by anthonyyuan** [comment]
Thank u !

**Comment by anthonyyuan** [comment]
can u tell me how to replace it  !  for example dlib
