### ISSUE TITLE
question

### ISSUE THREAD

**Issue by wx641242716** [junyanz/FaceDemo#4]
I can't cmake success, about opencv: just excute sudo apt-get libopencv-dev? don't install opencv?

**Comment by junyanz** [comment]
It should be enough. See more details [here](http://milq.github.io/install-opencv-ubuntu-debian/). Could you run basic opencv demo code?

**Comment by wx641242716** [comment]
i have succeed in running demo,thank you.just reinstall the system

**Comment by junyanz** [comment]
Great to hear that.
