### ISSUE TITLE
question

### ISSUE THREAD

**Issue by sunmiaobo** [junyanz/FaceDemo#5]
There are details about the program?

**Comment by junyanz** [comment]
Please refer to README for the details.

**Comment by sunmiaobo** [comment]
What I mean is that the program contents related introduction?

**Comment by junyanz** [comment]
Unfortunately there is no documentation for each cpp/header file. The src/main.cpp is the main function in this program. You can also refer to the [paper](https://people.eecs.berkeley.edu/~junyanz/projects/mirrormirror/mirrormirror_small.pdf) Section 4.2 for more technical details.

**Comment by sunmiaobo** [comment]
get!!!   thank you!!
